from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass(frozen=True)
class NewsSource:
    id: str
    name: str
    country: str
    language: str
    feeds: List[str]
    homepage: str


# Curated RSS endpoints per country/language. These are intentionally broad
# to maximize general news coverage.
ALLOWED_COUNTRIES = {
    "es-CO",
    "es-AR",
    "es-MX",
    "es-CL",
    "es-EC",
    "es-PE",
    "en-US",
    "es-ES",
}


SOURCES: List[NewsSource] = [
    NewsSource(
        id="es-es-elpais",
        name="El País",
        country="es-ES",
        language="es",
        feeds=["https://elpais.com/rss/elpais/portada.xml"],
        homepage="https://elpais.com",
    ),
    NewsSource(
        id="es-es-elmundo",
        name="El Mundo",
        country="es-ES",
        language="es",
        feeds=["https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml"],
        homepage="https://www.elmundo.es",
    ),
    NewsSource(
        id="es-es-abc",
        name="ABC",
        country="es-ES",
        language="es",
        feeds=["https://www.abc.es/rss/feeds/abcPortada.xml"],
        homepage="https://www.abc.es",
    ),
    NewsSource(
        id="es-es-lavanguardia",
        name="La Vanguardia",
        country="es-ES",
        language="es",
        feeds=["https://www.lavanguardia.com/rss/home.xml"],
        homepage="https://www.lavanguardia.com",
    ),
    NewsSource(
        id="es-es-20minutos",
        name="20 Minutos",
        country="es-ES",
        language="es",
        feeds=["https://www.20minutos.es/rss"],
        homepage="https://www.20minutos.es",
    ),
    NewsSource(
        id="es-es-elconfidencial",
        name="El Confidencial",
        country="es-ES",
        language="es",
        feeds=["https://rss.elconfidencial.com/espana/"],
        homepage="https://www.elconfidencial.com",
    ),
    NewsSource(
        id="es-es-okdiario",
        name="OKDiario",
        country="es-ES",
        language="es",
        feeds=["https://okdiario.com/feed"],
        homepage="https://okdiario.com",
    ),
    NewsSource(
        id="es-es-europapress",
        name="Europa Press",
        country="es-ES",
        language="es",
        feeds=["https://www.europapress.es/rss/rss.aspx"],
        homepage="https://www.europapress.es",
    ),
    NewsSource(
        id="es-es-efe",
        name="Agencia EFE",
        country="es-ES",
        language="es",
        feeds=["https://www.efe.com/efe/espana/rss/2"],
        homepage="https://www.efe.com",
    ),
    NewsSource(
        id="es-ar-lanacion",
        name="La Nación",
        country="es-AR",
        language="es",
        feeds=["https://www.lanacion.com.ar/rss/canal/portada-completa/"],
        homepage="https://www.lanacion.com.ar",
    ),
    NewsSource(
        id="es-ar-clarin",
        name="Clarín",
        country="es-AR",
        language="es",
        feeds=["https://www.clarin.com/rss/lo-ultimo/"],
        homepage="https://www.clarin.com",
    ),
    NewsSource(
        id="es-ar-infobae",
        name="Infobae",
        country="es-AR",
        language="es",
        feeds=["https://www.infobae.com/feeds/rss/?output=xml"],
        homepage="https://www.infobae.com",
    ),
    NewsSource(
        id="es-ar-perfil",
        name="Perfil",
        country="es-AR",
        language="es",
        feeds=["https://www.perfil.com/feed/"],
        homepage="https://www.perfil.com",
    ),
    NewsSource(
        id="es-ar-cronista",
        name="Cronista",
        country="es-AR",
        language="es",
        feeds=["https://www.cronista.com/files/rss/ultimas-noticias.xml"],
        homepage="https://www.cronista.com",
    ),
    NewsSource(
        id="es-ar-tn",
        name="Todo Noticias",
        country="es-AR",
        language="es",
        feeds=["https://www.tn.com.ar/rss.xml"],
        homepage="https://tn.com.ar",
    ),
    NewsSource(
        id="es-ar-eldestape",
        name="El Destape",
        country="es-AR",
        language="es",
        feeds=["https://www.eldestapeweb.com/rss/"],
        homepage="https://www.eldestapeweb.com",
    ),
    NewsSource(
        id="es-ar-minutouno",
        name="Minuto Uno",
        country="es-AR",
        language="es",
        feeds=["https://www.minutouno.com/rss"],
        homepage="https://www.minutouno.com",
    ),
    NewsSource(
        id="es-ar-iprofesional",
        name="iProfesional",
        country="es-AR",
        language="es",
        feeds=["https://www.iprofesional.com/rss"],
        homepage="https://www.iprofesional.com",
    ),
    NewsSource(
        id="es-ar-losandes",
        name="Los Andes",
        country="es-AR",
        language="es",
        feeds=["https://www.losandes.com.ar/feed"],
        homepage="https://www.losandes.com.ar",
    ),
    NewsSource(
        id="es-ar-lavoz",
        name="La Voz",
        country="es-AR",
        language="es",
        feeds=["https://www.lavoz.com.ar/rss/portada.xml"],
        homepage="https://www.lavoz.com.ar",
    ),
    NewsSource(
        id="es-ar-diariouno",
        name="Diario Uno",
        country="es-AR",
        language="es",
        feeds=["https://www.diariouno.com.ar/rss.xml"],
        homepage="https://www.diariouno.com.ar",
    ),
    NewsSource(
        id="es-ar-elliberal",
        name="El Liberal",
        country="es-AR",
        language="es",
        feeds=["https://www.elliberal.com.ar/rss/rss.xml"],
        homepage="https://www.elliberal.com.ar",
    ),
    NewsSource(
        id="es-ar-eldia",
        name="El Día",
        country="es-AR",
        language="es",
        feeds=["https://www.eldia.com/rss/eldia.xml"],
        homepage="https://www.eldia.com",
    ),
    NewsSource(
        id="es-ar-eltribuno",
        name="El Tribuno",
        country="es-AR",
        language="es",
        feeds=["https://www.eltribuno.com/rss/rss.xml"],
        homepage="https://www.eltribuno.com",
    ),
    NewsSource(
        id="es-ar-pagina12",
        name="Página/12",
        country="es-AR",
        language="es",
        feeds=["https://www.pagina12.com.ar/rss/portada/"],
        homepage="https://www.pagina12.com.ar",
    ),
    NewsSource(
        id="es-ar-ambito",
        name="Ámbito",
        country="es-AR",
        language="es",
        feeds=["https://www.ambito.com/rss/"],
        homepage="https://www.ambito.com",
    ),
    NewsSource(
        id="es-co-eltiempo",
        name="El Tiempo",
        country="es-CO",
        language="es",
        feeds=["https://www.eltiempo.com/rss/colombia.xml", "https://www.eltiempo.com/rss/mundo.xml"],
        homepage="https://www.eltiempo.com",
    ),
    NewsSource(
        id="es-co-elespectador",
        name="El Espectador",
        country="es-CO",
        language="es",
        feeds=["https://www.elespectador.com/rss/"],
        homepage="https://www.elespectador.com",
    ),
    NewsSource(
        id="es-co-semana",
        name="Semana",
        country="es-CO",
        language="es",
        feeds=["https://www.semana.com/rss/"],
        homepage="https://www.semana.com",
    ),
    NewsSource(
        id="es-co-caracol",
        name="Caracol",
        country="es-CO",
        language="es",
        feeds=["https://caracol.com.co/rss/portada.xml"],
        homepage="https://caracol.com.co",
    ),
    NewsSource(
        id="es-co-rcn",
        name="RCN Radio",
        country="es-CO",
        language="es",
        feeds=["https://www.rcnradio.com/feed"],
        homepage="https://www.rcnradio.com",
    ),
    NewsSource(
        id="es-co-bluradio",
        name="Blu Radio",
        country="es-CO",
        language="es",
        feeds=["https://www.bluradio.com/rss.xml"],
        homepage="https://www.bluradio.com",
    ),
    NewsSource(
        id="es-mx-eluniversal",
        name="El Universal",
        country="es-MX",
        language="es",
        feeds=["https://www.eluniversal.com.mx/rss.xml"],
        homepage="https://www.eluniversal.com.mx",
    ),
    NewsSource(
        id="es-mx-milenio",
        name="Milenio",
        country="es-MX",
        language="es",
        feeds=["https://www.milenio.com/rss.xml"],
        homepage="https://www.milenio.com",
    ),
    NewsSource(
        id="es-mx-proceso",
        name="Proceso",
        country="es-MX",
        language="es",
        feeds=["https://www.proceso.com.mx/feed/"],
        homepage="https://www.proceso.com.mx",
    ),
    NewsSource(
        id="es-mx-excelsior",
        name="Excélsior",
        country="es-MX",
        language="es",
        feeds=["https://www.excelsior.com.mx/rss.xml"],
        homepage="https://www.excelsior.com.mx",
    ),
    NewsSource(
        id="es-pe-elcomercio",
        name="El Comercio",
        country="es-PE",
        language="es",
        feeds=["https://elcomercio.pe/feed/"],
        homepage="https://elcomercio.pe",
    ),
    NewsSource(
        id="es-pe-larepublica",
        name="La República",
        country="es-PE",
        language="es",
        feeds=["https://larepublica.pe/feed/"],
        homepage="https://larepublica.pe",
    ),
    NewsSource(
        id="es-pe-andina",
        name="Agencia Andina",
        country="es-PE",
        language="es",
        feeds=["https://andina.pe/rss/rss.aspx"],
        homepage="https://andina.pe",
    ),
    NewsSource(
        id="es-cl-latercera",
        name="La Tercera",
        country="es-CL",
        language="es",
        feeds=["https://www.latercera.com/arcio/rss/"],
        homepage="https://www.latercera.com",
    ),
    NewsSource(
        id="es-cl-emol",
        name="Emol",
        country="es-CL",
        language="es",
        feeds=["http://www.emol.com/rss/rss.asp"],
        homepage="https://www.emol.com",
    ),
    NewsSource(
        id="es-cl-cooperativa",
        name="Cooperativa",
        country="es-CL",
        language="es",
        feeds=["https://www.cooperativa.cl/noticias/site/tax/port/all/rss_3_1__1.xml"],
        homepage="https://www.cooperativa.cl",
    ),
    NewsSource(
        id="es-cl-biobio",
        name="BioBioChile",
        country="es-CL",
        language="es",
        feeds=["https://www.biobiochile.cl/lista/feed/"],
        homepage="https://www.biobiochile.cl",
    ),
    NewsSource(
        id="es-cl-adn",
        name="ADN Radio",
        country="es-CL",
        language="es",
        feeds=["https://www.adnradio.cl/feed"],
        homepage="https://www.adnradio.cl",
    ),
    NewsSource(
        id="es-cl-24horas",
        name="24 Horas",
        country="es-CL",
        language="es",
        feeds=["https://www.24horas.cl/rss"],
        homepage="https://www.24horas.cl",
    ),
    NewsSource(
        id="es-cl-elmostrador",
        name="El Mostrador",
        country="es-CL",
        language="es",
        feeds=["https://www.elmostrador.cl/feed/"],
        homepage="https://www.elmostrador.cl",
    ),
    NewsSource(
        id="es-ec-eluniverso",
        name="El Universo",
        country="es-EC",
        language="es",
        feeds=["https://www.eluniverso.com/rss/"],
        homepage="https://www.eluniverso.com",
    ),
    NewsSource(
        id="es-ec-elcomercioec",
        name="El Comercio (EC)",
        country="es-EC",
        language="es",
        feeds=["https://www.elcomercio.com/feed/"],
        homepage="https://www.elcomercio.com",
    ),
    NewsSource(
        id="es-ec-primicias",
        name="Primicias",
        country="es-EC",
        language="es",
        feeds=["https://www.primicias.ec/rss/"],
        homepage="https://www.primicias.ec",
    ),
    NewsSource(
        id="es-ec-lahora",
        name="La Hora",
        country="es-EC",
        language="es",
        feeds=["https://www.lahora.com.ec/feed/"],
        homepage="https://www.lahora.com.ec",
    ),
    NewsSource(
        id="es-ec-metro",
        name="Metro Ecuador",
        country="es-EC",
        language="es",
        feeds=["https://www.metroecuador.com.ec/rss"],
        homepage="https://www.metroecuador.com.ec",
    ),
    NewsSource(
        id="es-ve-elnacional",
        name="El Nacional",
        country="es-VE",
        language="es",
        feeds=["https://www.elnacional.com/feed/"],
        homepage="https://www.elnacional.com",
    ),
    NewsSource(
        id="es-ve-ultimasnoticias",
        name="Últimas Noticias",
        country="es-VE",
        language="es",
        feeds=["https://ultimasnoticias.com.ve/feed/"],
        homepage="https://ultimasnoticias.com.ve",
    ),
    NewsSource(
        id="es-ve-2001",
        name="Diario 2001",
        country="es-VE",
        language="es",
        feeds=["https://2001online.com/feed"],
        homepage="https://2001online.com",
    ),
    NewsSource(
        id="es-ve-lapatilla",
        name="La Patilla",
        country="es-VE",
        language="es",
        feeds=["https://www.lapatilla.com/feed/"],
        homepage="https://www.lapatilla.com",
    ),
    NewsSource(
        id="es-ve-runrun",
        name="RunRunes",
        country="es-VE",
        language="es",
        feeds=["https://runrun.es/feed/"],
        homepage="https://runrun.es",
    ),
    NewsSource(
        id="es-ve-talcual",
        name="Tal Cual",
        country="es-VE",
        language="es",
        feeds=["https://talcualdigital.com/feed/"],
        homepage="https://talcualdigital.com",
    ),
    NewsSource(
        id="es-ve-efectococuyo",
        name="Efecto Cocuyo",
        country="es-VE",
        language="es",
        feeds=["https://efectococuyo.com/feed/"],
        homepage="https://efectococuyo.com",
    ),
    NewsSource(
        id="es-us-ap",
        name="Associated Press",
        country="en-US",
        language="en",
        feeds=["https://apnews.com/hub/ap-top-news?output=rss"],
        homepage="https://apnews.com",
    ),
    NewsSource(
        id="es-es-bbcmundo",
        name="BBC Mundo",
        country="global",
        language="es",
        feeds=["https://feeds.bbci.co.uk/mundo/rss.xml"],
        homepage="https://www.bbc.com/mundo",
    ),
    NewsSource(
        id="es-es-dw",
        name="DW Español",
        country="global",
        language="es",
        feeds=["https://rss.dw.com/rdf/rss-es-all"],
        homepage="https://www.dw.com/es",
    ),
    NewsSource(
        id="es-us-npr",
        name="NPR",
        country="en-US",
        language="en",
        feeds=["https://feeds.npr.org/1001/rss.xml"],
        homepage="https://www.npr.org",
    ),
    NewsSource(
        id="es-us-reuters",
        name="Reuters World",
        country="en-US",
        language="en",
        feeds=["https://www.reutersagency.com/feed/?best-topics=world&post_type=best"],
        homepage="https://www.reuters.com",
    ),
    NewsSource(
        id="es-us-nytimes",
        name="The New York Times",
        country="en-US",
        language="en",
        feeds=["https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"],
        homepage="https://www.nytimes.com",
    ),
    NewsSource(
        id="es-us-cnn",
        name="CNN Top Stories",
        country="en-US",
        language="en",
        feeds=["http://rss.cnn.com/rss/edition.rss"],
        homepage="https://www.cnn.com",
    ),
    NewsSource(
        id="es-us-fox",
        name="Fox News Latest",
        country="en-US",
        language="en",
        feeds=["https://moxie.foxnews.com/google-publisher/latest.xml"],
        homepage="https://www.foxnews.com",
    ),
    NewsSource(
        id="es-us-nbc",
        name="NBC News",
        country="en-US",
        language="en",
        feeds=["https://feeds.nbcnews.com/nbcnews/public/news"],
        homepage="https://www.nbcnews.com",
    ),
    NewsSource(
        id="es-us-abcnews",
        name="ABC News",
        country="en-US",
        language="en",
        feeds=["https://abcnews.go.com/abcnews/topstories"],
        homepage="https://abcnews.go.com",
    ),
    NewsSource(
        id="es-us-cbs",
        name="CBS News",
        country="en-US",
        language="en",
        feeds=["https://www.cbsnews.com/latest/rss/main"],
        homepage="https://www.cbsnews.com",
    ),
    NewsSource(
        id="es-us-usatoday",
        name="USA Today",
        country="en-US",
        language="en",
        feeds=["https://rssfeeds.usatoday.com/usatoday-NewsTopStories"],
        homepage="https://www.usatoday.com",
    ),
    NewsSource(
        id="es-uy-elobservador",
        name="El Observador",
        country="es-UY",
        language="es",
        feeds=["https://www.elobservador.com.uy/rss/portada.xml"],
        homepage="https://www.elobservador.com.uy",
    ),
    NewsSource(
        id="es-bo-lapaz",
        name="La Razón (Bolivia)",
        country="es-BO",
        language="es",
        feeds=["https://www.la-razon.com/feed/"],
        homepage="https://www.la-razon.com",
    ),
    NewsSource(
        id="es-py-abc",
        name="ABC Color",
        country="es-PY",
        language="es",
        feeds=["https://www.abc.com.py/rss/"],
        homepage="https://www.abc.com.py",
    ),
    NewsSource(
        id="global-techcrunch",
        name="TechCrunch",
        country="global",
        language="en",
        feeds=["https://techcrunch.com/feed/"],
        homepage="https://techcrunch.com",
    ),
    NewsSource(
        id="global-wired",
        name="Wired",
        country="global",
        language="en",
        feeds=["https://www.wired.com/feed/rss"],
        homepage="https://www.wired.com",
    ),
    NewsSource(
        id="global-arstechnica",
        name="Ars Technica",
        country="global",
        language="en",
        feeds=["https://feeds.arstechnica.com/arstechnica/index"],
        homepage="https://arstechnica.com",
    ),
    NewsSource(
        id="global-mashable",
        name="Mashable",
        country="global",
        language="en",
        feeds=["https://mashable.com/feed/"],
        homepage="https://mashable.com",
    ),
    NewsSource(
        id="es-es-marca",
        name="Marca",
        country="es-ES",
        language="es",
        feeds=["https://e00-marca.uecdn.es/rss/portada.xml"],
        homepage="https://www.marca.com",
    ),
    NewsSource(
        id="es-us-espn",
        name="ESPN",
        country="en-US",
        language="en",
        feeds=["https://www.espn.com/espn/rss/news"],
        homepage="https://www.espn.com",
    ),
    NewsSource(
        id="es-ar-tyc",
        name="TyC Sports",
        country="es-AR",
        language="es",
        feeds=["https://www.tycsports.com/rss.xml"],
        homepage="https://www.tycsports.com",
    ),
]


SUPPORTED_COUNTRIES = sorted(ALLOWED_COUNTRIES)


def sources_for_country(country: str) -> List[NewsSource]:
    normalized = country.strip()
    matches = [
        s
        for s in active_sources()
        if s.country.lower() == normalized.lower()
    ]
    return matches


# Disable feeds that are returning consistent 404/403 to reduce noise.
DISABLED_SOURCE_IDS = {
}


def active_sources() -> List[NewsSource]:
    return [
        s
        for s in SOURCES
        if s.country in ALLOWED_COUNTRIES and s.id not in DISABLED_SOURCE_IDS
    ]
